### ISSUE TITLE
Status 204 throws json error

### ISSUE THREAD

**Issue by pitakill** [klis87/redux-saga-requests#106]
https://github.com/klis87/redux-saga-requests/blob/db0a9bdc6c2edf5676df564dacfdfcdc4ab5899b/packages/redux-saga-requests-fetch/src/fetch-api-driver.js#L5

In this line if the `response.status` is `204`, the code assumes a `response.json()` and Throws a Error because there is no json to parse. 

With this snippet works:

```js
const statusEmptyContent = [204, 205];

const prepareSuccessPayload = (response, { responseType = 'json' }) => {
  if (responseTypes.indexOf(responseType) === -1) {
    throw new Error(
      "responseType must be one of the following: 'arraybuffer', 'blob', 'formData', 'json', 'text'",
    );
  }

  if (statusEmptyContent.indexOf(response.status) >= 0) return

  return response[responseType]();
};

```

**Comment by klis87** [comment]
btw, did you try setting `responseType` to `text`?

**Comment by klis87** [comment]
Actually you can use `responseType: null` since this release of Fetch driver - https://github.com/klis87/redux-saga-requests/releases/tag/redux-saga-requests-fetch%400.7.0
