### ISSUE TITLE
successAction from action

### ISSUE THREAD

**Issue by mapreal19** [klis87/redux-saga-requests#125]
Is it possible to get the successAction (or errorAction) from a defined action? I'd like to have access to them for testing reducers.

Example:
```
import { successAction } from 'redux-saga-requests';

import { FETCH_PHOTO } from './constants';

export const fetchPhoto = id => ({
  type: FETCH_PHOTO,
  request: { url: `/photos/${id}` },
});

export const fetchPhotoSucceeded = successAction(FETCH_PHOTO);
```

Does it make sense? I'd then use this action on my tests: `fetchPhotoSucceeded(myData, myMeta)`

pd: nice library btw :)

**Comment by klis87** [comment]
You can see such actions in https://github.com/klis87/redux-saga-requests/blob/master/packages/redux-saga-requests/src/actions.js#L11

It is not part of public API actually, but you can still import it like `import { successAction } from 'redux-saga-requests/actions'`

We might reeport it from `index.js` if there is demand for it, but I am not sure about it as I would prefer to keep public API to minimum

**Comment by mapreal19** [comment]
ok! Let's wait then and see if others will need this

**Comment by klis87** [comment]
Just a heads up - 1 thing on my roadmap is to make this library super easy to test, if using those actions is recommended and necessary to test easily, then I will reexport it for sure.

**Comment by mapreal19** [comment]
As I'm experiencing in one app we make sure to cover our reducers with unit tests and is a common case respond to a fetchSucceded action so I think it'll be useful. 

What I did for now is to define a `fetchPhotoSucceded` for my tests: 

```
const fetchPhotoSucceeded = (data, meta) => ({
  type: success(types.fetchPhoto),
  data,
  meta,
});
```

As you had it here the response: https://github.com/klis87/redux-saga-requests#successful-response

**Comment by klis87** [comment]
You could do it like:
```js
import { successAction } from 'redux-saga-requests/actions';

export const fetchPhoto = id => ({
  type: FETCH_PHOTO,
  request: { url: `/photos/${id}` },
});

const someMockData = {};

export const fetchPhotoSucceeded = successAction(fetchPhoto('someId'), someMockData);
```

This should work and save u some time.

**Comment by mapreal19** [comment]
@klis87 nice!
