### ISSUE TITLE
Abort request in `onRequest`

### ISSUE THREAD

**Issue by burgalon** [klis87/redux-saga-requests#146]
Hi Konrad,

Thank you for publishing redux-saga-requests!

I'm trying to abort requests in the onRequest hook and I'm either not sure what's the right way to do it, or maybe the redux-saga-requests onRequest API should be changed to support it:

Here's the scenario:
```
function* onRequestSaga(axiosInstance, request, action) {
  if (action.confirm) {
    const confirmed = yield call(confirmSaga, action.confirm);
    if (!confirmed) {
      // option 1 - yields a console exception
      throw new CancelRequest('Aborted by confirmation dialog');
     // option 2 - return error - request still tried to be dispatched and the exception is swollen - see attached screenshot below
      return { error: new CancelRequest('Aborted by confirmation dialog'))
      // dispatch abort - doesn't abort the request
      yield put({
          type: abort(action.type),
          meta: {
            requestAction: action,
          },
        })
    }
  }
  return request;
}
```

any ideas?

![image](https://user-images.githubusercontent.com/47217/43208748-c2ab41c0-9033-11e8-9558-735b73e9fa4b.png)

**Comment by klis87** [comment]
Hi @burgalon !

Dispatching `abort` action is just for notification purposes. Also, you cannot actually abort request in `onRequestSaga`, as request didnt even started, this intercepts it before it is executed so u can add some headers etc.

What we could do is to allow throwing or returning null in `onRequestInterceptor`, but maybe it is not necessery.

See 2 possible options:
- just dont dispatch request action when `action.confirm` is `true`
- see https://github.com/klis87/redux-saga-requests#watchrequests `abortOn` option, you could easily dispatch `CANCEL_SOME_ACTION` and  `watchrequests` will abort a proper request for you

**Comment by burgalon** [comment]
what do you mean by the first option? How do I not dispatch it if it's intercepted in the onRequest?

**Comment by burgalon** [comment]
as for the second option, the watchRequest(... abortOn) is global, and does not allow me to specify a specific action (unless I'll do a dictionary of all actions in the watchRequest....
)

**Comment by klis87** [comment]
can you please give me your usecase when do you wanna abort requests?

**Comment by klis87** [comment]
I mean just higher level overview as I just feel there might be a simpler solution

**Comment by burgalon** [comment]
use case: i would like to provide an easy way in the action creator to set a flag that will require the user to confirm a dialog (like [here](https://decembersoft.com/posts/a-redux-saga-implementation-of-modal-confirmation-dialogs-in-react-redux/))

**Comment by klis87** [comment]
So it is like a modal `Are u sure u wanna delete this item? Yes no question`?

**Comment by burgalon** [comment]
yap

**Comment by klis87** [comment]
so you should just dispatch request action only once user clicks `yes` button, request should even be sent at all before this, so there is no need to abort it

**Comment by klis87** [comment]
@burgalon did you had a chance to test it?

**Comment by burgalon** [comment]
hey I'm check it just now:
for the confirmation this is a very good option!. 
A different scenario which I have at hand, is for example, that the onRequest callback detects that it's missing authorization token, and needs to switch to the login page.
How would I go about it? I guess I still need to cancel the request in this scenario

**Comment by burgalon** [comment]
hey @klis87 - I've followed you suggestion for wrapping the requestAction with a prior confirmAction which seems to be working great and can also be applied to none redux-requests actions, which is great.
Thank you for your advice!
