### ISSUE TITLE
createDriver undefined in redux-saga-requests-axios

### ISSUE THREAD

**Issue by inconduit** [klis87/redux-saga-requests#153]
saw a commit yesterday, maybe something got broken in exports?

createDriver doesn't seem to be exported  from redux-saga-requests-axios.  i'm developing a project with react-redux-boilerplate as a basis. so to reproduce for my env (using node 8.9.0):

```
git clone git@github.com:flexdinesh/react-redux-boilerplate.git
npm install axios && npm install redux-saga-requests && npm install redux-saga-requests-axios
```

in src/app.js, add
```
import { createRequestInstance, watchRequests } from 'redux-saga-requests';
import { createDriver } from 'redux-saga-requests-axios';
console.log('createDriver', createDriver); 
// createDriver undefined
```

and the warning in chrome i see is:
```
./app/app.js 40:28-40"export 'createDriver' was not found in 'redux-saga-requests-axios' @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js
```

**Comment by inconduit** [comment]
great, that worked for now, thanks for the quick reply

**Comment by klis87** [comment]
@inconduit You can use new syntax with `createDriver` in new version `0.16.0`
