### ISSUE TITLE
Override requests-promise-middleware when auto

### ISSUE THREAD

**Issue by nemosupremo** [klis87/redux-saga-requests#179]
We use `requests-promise-middleware` a lot, with `auto`, however one request in our code base does not need to be promisified, and also gets aborted a lot - which leads to a lot of "errors" in the console.

I'd like to be able to set `isPromise` explicitly to false to disable this behavior. I thought I would ask before making a PR.

https://github.com/klis87/redux-saga-requests/blob/bb40be382d72dcef76bda493d797f1cf59ea28dd/packages/redux-saga-requests/src/middleware.js#L8

would become something like

```js
const shouldActionBePromisified = (action, auto) =>
  (auto && !(action.meta && action.meta.asPromise === false)) || (action.meta && action.meta.asPromise);
```

**Comment by klis87** [comment]
@nemosupremo really nice idea, I noticed this issue too in #93 and partially I fixed it by `auto: false`, but I didn't think about possibility to overwrite `auto`. I would happily accept such a PR!
