### ISSUE TITLE
Compatible with Redux Saga 1.0.0 and up?

### ISSUE THREAD

**Issue by Slapbox** [klis87/redux-saga-requests#180]
Is this library compatible with Redux-Saga 1.0.0 and up? Thanks for all your hard work!

**Comment by Slapbox** [comment]
Nope =(

**Comment by klis87** [comment]
@Slapbox I didnt even try it, as redux-saga 1 is in beta, so my plan actually was to wait until it is out of beta and try it then. The problem is that otherwise I would need to maintain 2 versions while I have sooo many plans for features, so focusing on version 1 would delay me.

Do you know whats the problem though? Maybe it wouldn't be so time consuming?

**Comment by Slapbox** [comment]
Wow talk about a quick response!

I don't know for sure what the problem is, but I can provide the error message I get on the "basic" example.

```
utils.js:250 TypeError: Cannot read property 'method' of undefined
    at isGetRequest (sagas.js:279)
    at Object.takeLatest (sagas.js:287)
    at watchRequests$ (sagas.js:358)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:288)
    at Generator.prototype.(:3000/anonymous function) [as next] (http://localhost:3000/main.js:5152:21)
    at next (proc.js:332)
    at currCb (proc.js:451)
    at runEffect (proc.js:411)
    at digestEffect (proc.js:492) ""
log @ utils.js:250
logError @ proc.js:209
end @ proc.js:376
abort @ proc.js:76
task.cont @ proc.js:91
next @ proc.js:350
currCb @ proc.js:451
end @ proc.js:385
abort @ proc.js:76
task.cont @ proc.js:91
next @ proc.js:350
currCb @ proc.js:451
runEffect @ proc.js:411
digestEffect @ proc.js:492
next @ proc.js:336
proc @ proc.js:284
resolveIterator @ proc.js:512
runEffect @ proc.js:408
digestEffect @ proc.js:492
next @ proc.js:336
currCb @ proc.js:451
runEffect @ proc.js:411
digestEffect @ proc.js:492
next @ proc.js:336
proc @ proc.js:284
runSaga @ runSaga.js:61
configureStore @ index.js:38
./src/index.js @ index.js:9
__webpack_require__ @ bootstrap:724
fn @ bootstrap:101
0 @ main.js:54170
__webpack_require__ @ bootstrap:724
(anonymous) @ bootstrap:791
(anonymous) @ bootstrap:791
utils.js:250 The above error occurred in task rootSaga
    created by rootSaga
 ```

I foolishly tried working with it, forgetting that the version of Redux-Saga I use is not the latest stable, and I was getting a different error: `"call: argument fn is undefined"`

Hope this gives any insight, and thanks again for your hard work!

**Comment by klis87** [comment]
@Slapbox is there a specific reason u use redux-saga beta, or it would be ok for you to downgrade to 0.16 for now?

**Comment by klis87** [comment]
@Slapbox I tried to investigate beta usage but I don't understand what's causing the issue. See https://github.com/redux-saga/redux-saga/issues/1702 for reference

**Comment by Slapbox** [comment]
Ah thanks for taking a look @klis87. To answer your question, I'm just way too deep into Redux Saga 1.0.0 to reverse course now.

**Comment by klis87** [comment]
@Slapbox It turned out that the culprit was dev dependency in `redux-saga-requests` package. The only think that I had to change to make everything work was `delay` import. See https://github.com/klis87/redux-saga-requests/releases/tag/redux-saga-requests%400.20.0
