### ISSUE TITLE
on GET requests params in request.data are not passed in the request

### ISSUE THREAD

**Issue by inconduit** [klis87/redux-saga-requests#183]
using axios, an action as defined below does not pass `offset` into the resulting network request. is the data payload intentionally stripped on GETs?

```
export function loadThing(offset) {
  return {
    type: LOAD_THING_REQUEST,
    request: {
      data: { offset },
      url: 'https://someapi.com'
    }
  };
}
```

**Comment by klis87** [comment]
@inconduit this is how `axios` works, and generally `http`, u can pass query string to `GET` request, which will be part of url, like in your case: `http://url?offset=1`, you can do this by:
```js
export function loadThing(offset) {
  return {
    type: LOAD_THING_REQUEST,
    request: {
      params: { offset },
      url: 'https://someapi.com'
    }
  };
}
params
```
