### ISSUE TITLE
Best Practice for Normalizr Implementation?

### ISSUE THREAD

**Issue by Flash619** [klis87/redux-saga-requests#218]
I am using this package for an app that relies on Normalizr and am curious if there is a way to run a normalization after a GET request on the response, prior to the success action being dispatched so that I may be able to easily hydrate data in my reducers?

edit

I think I figured out a way to do this using the onSuccess interceptor. 

```
function * onSuccessSaga (response, action) {
  switch (action.type) {
    case objectA.types.GET:
    case objectA.types.POST:
      response = normalize(response, schemas.objectA)
      break
    case objectB.types.GET:
    case objectB.types.POST:
    case objectB.types.PATCH:
      response = normalize(response, schemas.objectB)
      break
  }
  return response
}

```

**Comment by klis87** [comment]
Great you found the solution, you could also use `getData` in `requestsReducer` https://github.com/klis87/redux-saga-requests#reducers-arrow_up, or even you could adjust driver you use, for instance:
```js
import { createDriver } from 'redux-saga-requests-axios';
import axios from 'axios';

const prepareSuccessPayload = response => response.data; // adjust it

const myCustomDriver = {
  ...createDriver(axios),
  getSuccessPayload: (response) => {
    if (Array.isArray(response)) {
      return response.map(prepareSuccessPayload);
    },
};
```

But I think that reducer approach is the best one, because normalization is defined per entity type, so if you attach normalization logic to a given  `getData` in `requestsReducer`, you don't need to check which request this is, while in interceptor you will end up with switch with numerous case statements, which is not as scalable from code perspective.

**Comment by Flash619** [comment]
> Great you found the solution, you could also use `getData` in `requestsReducer` https://github.com/klis87/redux-saga-requests#reducers-arrow_up, or even you could adjust driver you use, for instance:
> 
> ```js
> import { createDriver } from 'redux-saga-requests-axios';
> import axios from 'axios';
> 
> const prepareSuccessPayload = response => response.data; // adjust it
> 
> const myCustomDriver = {
>   ...createDriver(axios),
>   getSuccessPayload: (response) => {
>     if (Array.isArray(response)) {
>       return response.map(prepareSuccessPayload);
>     },
> };
> ```
> 
> But I think that reducer approach is the best one, because normalization is defined per entity type, so if you attach normalization logic to a given `getData` in `requestsReducer`, you don't need to check which request this is, while in interceptor you will end up with switch with numerous case statements, which is not as scalable from code perspective.

I just thought I would give my two cents on why I chose interceptors. 

The only issue I can see with using the reducer method is if you have related models in your state. For example, lets say objectA typically includes nested objects, objectB and objectC when it is fetched. This means that objectB and objectC reducers will need to listen for an objectA fetch success action, and will all need to renormalize the same value for each reducer.

I chose the interceptor because it means normalization only happens once and that the value is normalized already before any reducer is called. Let me know if you get any new ideas from this perspective.

**Comment by klis87** [comment]
Looking from this perspective you are right, multiple reducers could rely on the same normalized response and you do normalization only once. The only one thing I could add is that if you organized your code into ducks (dividing by features), then you could put `normalizers.js` into  each module and import and use them where you have interceptor.

Then, your interceptor won't grow out of control.

**Comment by Flash619** [comment]
> Looking from this perspective you are right, multiple reducers could rely on the same normalized response and you do normalization only once. The only one thing I could add is that if you organized your code into ducks (dividing by features), then you could put `normalizers.js` into each module and import and use them where you have interceptor.
> 
> Then, your interceptor won't grow out of control.

That's what I originally did. :) I decided against that approach due to circular import issues. It made more sense to define all schemas in one file so I didn't have to deal with the mess of multiple objects possibly nesting one or another.

**Comment by Flash619** [comment]
I think we have enough ideas in here... Closing for now.

**Comment by klis87** [comment]
@Flash619 this library supports automatic normalisation now, so no Normalizr is necessary.

It works similar to GraphQL Apollo
