### ISSUE TITLE
Headers Missing On POST Requests?

### ISSUE THREAD

**Issue by Flash619** [klis87/redux-saga-requests#222]
Greetings Again! 

I'm trying to write a POST request to a login endpoint generated using [Loopback](https://loopback.io/). My action creator looks like this,

```javascript
export const login = (username, password) => ({
  type: types.LOGIN,
  request: {
    url: utils.genApiUrl(models.USER_PROFILE) + '/login',
    method: 'POST',
    body: JSON.stringify({ username, password }),
    headers: {
      'Content-Type': 'application/json'
    }
  }
})
```

This fails with a 400 error stating that the username or email key must be supplied in the body. I have confirmed this works with Postman as well as the Loopback API explorer. However, even when trying a static JSON string as the body value in my action creator Loopback continued to give the same error. I started looking deeper into the request, and it seems the headers property, specifically 'content-type' is not being passed on my request.

```
POST /api/user-profiles/login HTTP/1.1
Host: localhost:3000
Connection: keep-alive
Content-Length: 0
Accept: application/json, text/plain, */*
Origin: http://localhost:3000
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Referer: http://localhost:3000/login/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```

Content-Type is not listed above, which is likely why Loopback does not know how to parse the body of the request. Content-Length is also 0 which makes me think no content is actually being posted.

Also, here is a [link ](https://i.imgur.com/qlJxrsk.png) to an image showing request/response headers for the above request from Chrome's Network tab. 

EDIT

I'm using redux-saga-requests-axios.

**Comment by klis87** [comment]
Hi!
`redux-saga-requests-axios` is just small wrapper around `axios`, In `axios` you don't need to stringify body, try this:
```js
export const login = (username, password) => ({
  type: types.LOGIN,
  request: {
    url: utils.genApiUrl(models.USER_PROFILE) + '/login',
    method: 'POST',
    body: { username, password },
  }
})
```

**Comment by Flash619** [comment]
> Hi!
> `redux-saga-requests-axios` is just small wrapper around `axios`, In `axios` you don't need to stringify body, try this:
> 
> ```js
> export const login = (username, password) => ({
>   type: types.LOGIN,
>   request: {
>     url: utils.genApiUrl(models.USER_PROFILE) + '/login',
>     method: 'POST',
>     body: { username, password },
>   }
> })
> ```

I still get the same result.

[https://i.imgur.com/uJ4w0RR.png](https://i.imgur.com/uJ4w0RR.png)

[https://i.imgur.com/OnLwVHK.png](https://i.imgur.com/OnLwVHK.png)

**Comment by klis87** [comment]
Can u try to make successful request with using pure `axios`? Anywhere, from a component on mount, just to see what axios config is required to make it work, I bet that using axios directly with above config will trigger the same error.

**Comment by Flash619** [comment]
> Can u try to make successful request with using pure `axios`? Anywhere, from a component on mount, just to see what axios config is required to make it work, I bet that using axios directly with above config will trigger the same error.

Using axios directly works correctly with a 401 error 'Invalid Login'. This is expected given this is not a valid login. Below is the source I used to generate the request as well as an image link showing that the request included the proper content whereas the redux-saga-requests request did not.

```javascript
export const login = (username, password) => {
  axios({
    method: 'POST',
    url: utils.genApiUrl(models.USER_PROFILE) + '/login',
    data: { username, password },
    headers: {
      'Content-Type': 'application/json'
    }
  })
  return {}
}
```

[https://i.imgur.com/ftFpu6b.png](https://i.imgur.com/ftFpu6b.png)

**Comment by klis87** [comment]
could you pass authentication in pure axios version request so we could be sure it will get 200 response? 

Check axios driver source code: https://github.com/klis87/redux-saga-requests/blob/master/packages/redux-saga-requests-axios/src/axios-driver.js#L13

I don't do anything really in `sendRequest`, I just pass blindly config from redux action, with just additional `cancelToken` to support automatic aborts, so there is no really a way it could be axios driver fault.

Btw, try to remove
```js
headers: {
  'Content-Type': 'application/json'
}
```
I believe that `application/json` is axios default, I never set it and it always works.

If this doesn't help, inspect axios `error.config` to see exactly what config was used to make failing request, this could give us a hint what is broken.

**Comment by Flash619** [comment]
> error

Good news! I think I figured out the problem.

```javascript
export const login = (username, password) => ({
  type: types.LOGIN,
  request: {
    url: utils.genApiUrl(models.USER_PROFILE) + '/login',
    method: 'POST',
    body: { username, password }, // This should be 'data' not 'body'.
  }
})
```

Changing body to data fixed this issue. As you said, it was blindly copying the config, and axios expects a data key, not a body key to be passed.

**Comment by klis87** [comment]
Indeed, `body` is used in Fetch driver :D
