### ISSUE TITLE
Driver not adding headers dynamicly React-native

### ISSUE THREAD

**Issue by AfanasievN** [klis87/redux-saga-requests#223]
I have a stage when I add authorization token to my axios instance and when I want to make any request with it, headers are missing
Here is my rootSaga
<img width="427" alt="2019-01-29 18 37 11" src="https://user-images.githubusercontent.com/25581141/51924050-fc190000-23f4-11e9-8786-330aafb9c36d.png">

My axios service:
<img width="661" alt="2019-01-29 18 37 27" src="https://user-images.githubusercontent.com/25581141/51924092-118e2a00-23f5-11e9-9227-efec74c21681.png">

And place where I add my token. 
<img width="500" alt="2019-01-29 18 37 37" src="https://user-images.githubusercontent.com/25581141/51924123-1fdc4600-23f5-11e9-9eba-69764debe261.png">

Console.logs . Request missing headers that I've added later as a common(global axios header)
![2019-01-29 18 42 17](https://user-images.githubusercontent.com/25581141/51924496-c7f20f00-23f5-11e9-9d75-48d01dde24e8.png)

Any ideas? Suggestions?

**Comment by klis87** [comment]
It is hard for me to help without any repo/sandbox showing this issue, but I suspect that this might have something to do with axios instance mutations, which might be dangerous to do, you change it in place, so it is really hard to track how changing default header affects the rest of the app. This is one of the reasons Redux was invented ;) Did you think about a safer alternative, like `onRequest` interceptor?
```js
const addTokenToRequest = request => ({
  ...request,
  headers: {
    ...request.headers,
    Authorization: `Bearer ${window.localStorage.getItem('token')}`,
  },
});

function onRequest(request) {
  if (window.localStorage.getItem('token')) {
    request = addTokenToRequest(request);
  }

  return request;
}
```
This is just 1 way of doing it, you could keep the token in redux too and use `yield select` from `redux-saga/effects`. By using interceptor in your case your code will become cleaner, safer, and probably should send you proper headers :)

**Comment by AfanasievN** [comment]
@klis87 thank you, for your response.
I found the issue. It's was because of my asyncStorage error.
it is resolved.
