### ISSUE TITLE
Add ability to specify default value of reducer

### ISSUE THREAD

**Issue by megawac** [klis87/redux-saga-requests#229]
Currently we can specify the default to either null (`multiple: false`) or an empty array (`multiple: true`). However we may sometimes want the default to be something else. For my use case I am fetching a GeoJSON FeatureCollection, so I'd like my default to be `{type: "FeatureCollection", features: []}`.

I propose replacing the `multiple` option with a `getDefault` function which returns the default value. So, `getDefault: () => {your default}`

**Comment by klis87** [comment]
very nice idea, I never had such a use case for initial value, but we indeed need to support custom initial value. 

I like callback approach, but what do you think we wouldnt get rid of `multiple` option (works for 90%+ cases I guess and it is easier to use), and default for `getDefault` would be actually `return config.multiple`, so people could still use `multiple`, but they also could use lower level `getDefault` when necessary

**Comment by megawac** [comment]
I don't have strong opinions on whether multiple is preserved or not. I just suggested it because in the case of multiple the user could set `getDefault: Array`

**Comment by klis87** [comment]
nice trick with `Array`, problem is that it is not as obvious plus u cannot do the same to return `null`

so to confirm, let's do extra prop `getDefaultData` returning `config.multiple ? [] : null` as default, so it will be backward compatible change as `multiple` will be used indirectly. 

I will try to implement it over the weekend, but if you need it sooner, I recommend to solve it on selector layer for now, or, If u wish, I could accept PR with this change.

**Comment by megawac** [comment]
I have a hack fix for now in the intermediary layer I'm fine with that I can probably put that in tomorrow if you'd prefer

**Comment by klis87** [comment]
I am fine either way :) I will always happily accept PRs, but on the other hand over the weekend I am going to work on extending cache anyway, so I could to that on the occasion then.

**Comment by klis87** [comment]
@megawac thx! Published as `0.23.0` . Note that I renamed new prop to `getDefaultData`.
