### ISSUE TITLE
Remove 2nd argument (custom reducer) from requestsReducer

### ISSUE THREAD

**Issue by klis87** [klis87/redux-saga-requests#231]
Initially passing custom reducer to `requestsReducer` to allow adding extra state which then is merged with request state from this library seemed like good idea to me. Now I find it unnecessary. Why not just use separate reducer, listening for proper requests actions, which then could be merged with `combineReducers`? And you you really want to merge some custom state with request state, you can easily use selectors.

So, I think I will probably remove the possibility to pass custom reducer to `requestsReducer`, which unnecessarily makes thinks complicated and not always obvious. This will be especially important quite soon, as I am going to create higher level reducer, which will act like automatic `requestsReducer` for all your requests actions, so you won't need to define `requestsReducer` per action type anymore.

However, if you think that removing this is a bad idea, pls comment here

**Comment by klis87** [comment]
I guess it should work, but not everyone uses Redux-act. Actually I already thought about this and I think I should add sth like local operations to `requestsReducer`. Currently you can only define operations as other requests of method like `POST`, `DELETE`, but actually this should have support for other actions too. I will try to think of sth so that your case wouldn't even require writing additional reducer. 

Btw, you could just do `reset: [getFeaturesAction, resetState]` because it has 1st support to `redux-act` actions

**Comment by megawac** [comment]
True, I was doing some additional checks at one point, I never got around to swapping to that syntax :)

**Comment by klis87** [comment]
@megawac removed in newest `0.26.0` version, but you can use local mutation(operation) to update `data` with normal actions
