### ISSUE TITLE
Removing createRequestsReducer

### ISSUE THREAD

**Issue by klis87** [klis87/redux-saga-requests#235]
I am going to remove `createRequestsReducer`, because if you want to have a `requestsReducer` with different defaults, it is easy to do like below:
```js
import { requestsReducer } from 'redux-saga-requests';

const myRequestsReducer = config => requestsReducer({ multiple: true ...config });
```
so there is not point to have `createRequestsReducer` in this library.

Please comment here if you disagree for some reason, so I might change my mind.

**Comment by spacesuitdiver** [comment]
I think it'd be:
```
const myRequestsReducer = (...config) => requestsReducer({ multiple: true ...config });
```

That said this issue indirectly solved my problem, I'm game to remove it and compose it from `requestsReducer` instead.

**Comment by klis87** [comment]
Removed in `0.26.0`
