### ISSUE TITLE
getLastActionKey doesn't seem to work?

### ISSUE THREAD

**Issue by spacesuitdiver** [klis87/redux-saga-requests#239]
Hi,

I end up firing a bunch of actions to fetch some resources using:
```
yield all([put(fetchResource('abc123')), put(fetchResource('abc567'))]);
```

If fetchResource is a standard redux-saga-requests action I'd think I could prevent it from aborting the `abc567` request by formulating my request using the action creator below (I'm using FSA compatible actions) but it still seems to abort my requests. There doesn't seem to be a test written for request specific `getLastActionKey` so maybe this isn't working as expected?

```
export const fetchResource = resourceId => ({
    type: types.FETCH_RESOURCE,
    payload: {
        request: {
            url: `/resource/${resourceId}`,
        },
    },
    meta: {
        resourceId,
        getLastActionKey: action => action.type + action.meta.resourceId
    },
});
```

**Comment by klis87** [comment]
`getLastActionKey` should be passed to `watchRequests`, not to action meta, see https://github.com/klis87/redux-saga-requests#watchrequests

in your case it could be defined like:
`getLastActionKey: action => action.type + ((action.meta && action.meta.resourceId) || '')`

Then, if there is a pending request of a type `x`, it won't be cancelled if a new request `x` is fired with a different `action.meta.resourceId`. I guess this is what you want?

Alternatively, if you don't wanna cancel requests for a given type at all, just set `action.meta.takeLatest: false`

**Comment by klis87** [comment]
hmm, but aborting is a one thing, the problem is that I guess you wanna keep both resources in `requestsReducer`. It won't work with current setup because next response will override previous one.

See #165 for similar issue. I recommend the following pattern like I adviced there:
```js
const fetchResources = (resourcesIds) => ({
  type: 'FETCH_RESOURCES',
  request: resourcesIds.map(id => ({ url: /resource/${id} })),
});
```
In other words, you can use batched requests, so u pass array of configs to `request` instead of single config. It is mentioned in https://github.com/klis87/redux-saga-requests#motivation-arrow_up but I guess this could be a little better documented. Please let me know if that suits you.

**Comment by spacesuitdiver** [comment]
@klis87 oh cool, thank you for the response, I guess I assumed similar to how you could takeLatest you could modify the action key matching. I'll give the multiple requests thing a shot though as that seems like what I'm actually after. Thank you again!

**Comment by spacesuitdiver** [comment]
@klis87 one question, when using the request batching how do I get `meta` information into the action? In the example above I send in the `resourceId` in meta.

**Comment by klis87** [comment]
@spacesuitdiver the question is why do you need `resourceId` to be in meta if you wanna you bathing, is there any specific reason? as it might be not necessary anymore

**Comment by spacesuitdiver** [comment]
@klis87 sometimes we end up deriving an ID on the client and not using the one from the API, admittedly this is out of convention for this request so you're right, it might not be necessary.

**Comment by spacesuitdiver** [comment]
@klis87 for some reason when I use the batching as you've described it just tries to hit `/`.

```
{
  type: 'resources/FETCH_RESOURCES',
  payload: {
    request: [
      {
        url: '/resources/59a48fafe48c0d373742fd49'
      },
      {
        url: '/resources/57ce45bab13a7b8e79f420da'
      },
      {
        url: '/resources/5ab3dce992376516000ef03f'
      },
      {
        url: '/resources/5abbbc05be12b3160049ca4f'
      },
      {
        url: '/resources/5af317e80e81f31300522647'
      },
      {
        url: '/resources/5ab579bfa123a11600899d12'
      },
      {
        url: '/resources/5c8812cadc97e41e00b049c1'
      },
      {
        url: '/resources/553a9a48a1094d7a5eb91975'
      }
    ]
  }
}
```

**Comment by klis87** [comment]
it really should work, see https://github.com/klis87/redux-saga-requests/blob/master/examples/advanced/src/store/actions.js#L25 example, if it doesnt pls create an `CodeSandbox` example so I could take a look.

**Comment by spacesuitdiver** [comment]
@klis87 I tried the advanced example and it works fine but for the life of me I can't see what I'm doing differently in my project. This is a React Native project so not sure if maybe we are doing something that it's variant of fetch doesn't support? Any thoughts?

**Comment by klis87** [comment]
@spacesuitdiver the only thing that comes to my mind is that you use an interceptor and you don't take into account that you could get array of requests and responses, otherwise each action should be independent on another. 

Maybe try to do this batch fetch in a simple project, for example by adjusting fetch example. Then see if it works. If yes, you could use it to simplest possible react native project, I didn't test it but I guess that it should work there too. But you can never be sure.

**Comment by spacesuitdiver** [comment]
@klis87 thank you. We do use a request interceptor so I will double check that. This helps immensely.

**Comment by klis87** [comment]
I guess this could be it, as you might for instance transform array into object indexed by keys.
See https://github.com/klis87/redux-saga-requests/blob/master/packages/redux-saga-requests/src/helpers.js for small helper which is not documented yet, but it could save you one function form wirting yourself

**Comment by spacesuitdiver** [comment]
@klis87 thanks again, request/response as array was the issue.
