### ISSUE TITLE
Would something like `getData: false` be useful?

### ISSUE THREAD

**Issue by spacesuitdiver** [klis87/redux-saga-requests#243]
I'm using requestsReducer to at the very minimum make my error reductions consistent. I'm finding that during authentication we don't reduce any data into the store so we do something silly to override this like `getData: () => null`.

**Comment by klis87** [comment]
if you dont wanna data to be put to your store, I think this is optimal solution

**Comment by klis87** [comment]
In theory we could imlement `getData: false`, but it seems to me a rare use case, and you solution gets the job done, and I dont wanna complicate API

**Comment by spacesuitdiver** [comment]
Sounds good.

**Comment by klis87** [comment]
@spacesuitdiver actually now with networkReducer you can use `meta.asMutation: true`, which would force a request to be treated as mutation, and mutation(old operation) keeps only pending and error state, no data
