### ISSUE TITLE
Add support for a react container which supports multiple requests

### ISSUE THREAD

**Issue by megawac** [klis87/redux-saga-requests#246]
I find myself often needing to react to multiple requests operating in tandem. In particular I need to show a loading screen/error screen when any of these requests are in flight. Ideally I'd be able to use the `RequestContainer` however this only supports 1 request and it's not nice to nest them. In my particular case I need to react to 4 requests.

I see 3 options for this case: 1) nest `RequestContainers`, 2) Using custom code in my `mapStateToProps` and component to handle the states, 3) I decided to go along the path of creating a `MultipleRequestContainer`. The basic difference between the one major difference is it takes an array of requests to observer.

My implementation of this was pretty much coppied from the one you provided. Not sure if this is a common use case, I've reached for this hammer 4 times so far.

```js
import React from 'react';
import PropTypes from 'prop-types';

import _ from 'lodash';

export const MultipleRequestContainer = ({
  requests,
  children,
  component: Component,
  showLoaderDuringRefetch,
  noDataMessage,
  errorComponent: ErrorComponent,
  errorComponentProps,
  loadingComponent: LoadingComponent,
  loadingComponentProps,
  ...extraProps
}) => {
  if (showLoaderDuringRefetch && _.some(requests, (request) => request.pending > 0)) {
    return LoadingComponent ? (
      <LoadingComponent {...loadingComponentProps} />
    ) : null;
  }

  const error = _.find(requests, 'error');

  if (error) {
    return ErrorComponent ? (
      <ErrorComponent error={error} {...errorComponentProps} />
    ) : null;
  }

  const dataMap = _.mapValues(requests, 'data');

  return <Component {...dataMap} {...extraProps} />;
};

MultipleRequestContainer.defaultProps = {
  showLoaderDuringRefetch: true,
  noDataMessage: null,
  errorComponent: null,
  errorComponentProps: {},
  loadingComponent: null,
  loadingComponentProps: {}
};

MultipleRequestContainer.propTypes = {
  component: PropTypes.elementType.isRequired,
  requests: PropTypes.objectOf(
    PropTypes.shape({
      data: PropTypes.any,
      error: PropTypes.any,
      pending: PropTypes.number.isRequired,
    })
  ).isRequired,

  showLoaderDuringRefetch: PropTypes.bool,
  noDataMessage: PropTypes.node,
  errorComponent: PropTypes.elementType,
  errorComponentProps: PropTypes.objectOf(PropTypes.any),
  loadingComponent: PropTypes.elementType,
  loadingComponentProps: PropTypes.objectOf(PropTypes.any),
};
```

And the corresponding `ConnectedMultipleRequestContainer`:

```js
import { connect } from 'react-redux';
import PropTypes from 'prop-types';
import _ from 'lodash';

import { MultipleRequestContainer } from '.';

export const ConnectedMultipleRequestContainer = connect(
  (state, props) => ({ requests: _.pick(state, props.requests) })
)(MultipleRequestContainer);

const { requests, ...commonRequestContainerProps } = MultipleRequestContainer.propTypes;

ConnectedMultipleRequestContainer.propTypes = {
  ...commonRequestContainerProps,
  requests: PropTypes.arrayOf(PropTypes.string).isRequired,
};

```

**Comment by klis87** [comment]
Good idea, I also thought about something similar. Another approach would also involve React hooks, which I am going to add once react-redux adds then. This would solve nesting issue.

**Comment by klis87** [comment]
@megawac now you have access to React hooks, solving nesting issue. However I think this should be handled on selector level, which is especially easy now with `networkReducer` and `getQuery` selector creator.

You could for instance do:
```js
import { createSelector } from 'reselect';
import { getQuery } from 'redux-saga-requests';

const querySelector = createSelector(
  getQuery({ type: 'QUERY_A', multiple: true }),
  getQuery({ type: 'QUERY_B', multiple: true }),
  (queryA, queryB) => ({
    loading: queryA.loading || queryB.loading,
    error: queryA.error || queryB.error,
    data: [...queryA.data, ...queryB.data],
  }),
)
```

Then you could use this `querySelector` as `<Query requestSelector={querySelector}>`

Of course helper selector creators could be made to abstract this. Actually I am going to introduce some in future versions.

**Comment by megawac** [comment]
Interesting, I'm fine with that approach. Thanks.
