### ISSUE TITLE
Adding a validation hook as a precondtion to submitting an operation

### ISSUE THREAD

**Issue by megawac** [klis87/redux-saga-requests#247]
Hi,

I've hit a situation where I wanted to add validation logic as a precondtion to submitting a request through the library. Before submitting a request I want to run through a series of client side validations that must be met before the request is dispatched to the server.

I was what your thoughts are about validation in the library. My original plan was to dispatch a `put(createErrorAction(myRequestAction, myException))` to have the store updated with the validation error. The issue with this approach is pending would go from `0` -> `-1` as the request would of never initiated. I've included a summary of an early attempt at this below

-------------------

I already have a little saga wrapper that intercepts my requests and then dispatches the requests with some additional context from my store which is reused by about 30 operations. I was hoping I could add a hook in here to add a validation step if provided. Below is a snippet that I've updated to remove some buisness logic

```js
import { call, select, put } from 'redux-saga/effects';

import { createErrorAction } from 'redux-saga-requests/lib/actions';

/**
 * Creates a saga to intercept a request and pass the map to the action.
 * @param {action} requestAction: The request action to dispatch
 * @param {function} hasData({payload}) request to validate the the action was provided with data.
 *    Return false to avoid submitting the rpc call.
 */
export function createMapRequestSaga(requestAction, {
  validate = () => true,
}) {
  return function* updateMapSaga({ payload }) {
    const { loadedMap } = yield select((state) => state.maps);

    const request = requestAction({ ...payload, map: loadedMap });

    if (myMapIsValid()) {
      const exception = new InvalidMap(requestAction);
      yield put(createErrorAction(request, exception));
    } else if (!validate(payload)) {
      const exception = new MapValidationError(requestAction);
      yield put(createErrorAction(request, exception));
    }
    return yield call(sendRequest, request);
  };
}
```

This gets used as such

```js
  const mapRequestConfig = {
    validate: ({ [type]: features }) => validateFeatureCollection(features),
  };

  const setFeaturesAction = createAction(`set ${type}`);
  const _setFeaturesAction = createAction(`set ${type} internal`, ({ map, [type]: features }) => {
    return {
      request: {
        url: '/v2/maps/operations/',
        method: 'post',
        data: formatRPCCall(`set${typeCapitalized}`, {
          map_id: map.id,
          features,
        })
      },
    };
  }, ({ map, [type]: features }) => ({ map, features }));
  const setFeaturesSaga = createMapRequestSaga(_setFeaturesAction, mapRequestConfig);
```

**Comment by klis87** [comment]
Before going further into discussion:
1) By client side validation you mean things like user form input?
2) You want to use `createErrorAction` to store errors inside `requestReducer` or there is another reason?

**Comment by megawac** [comment]
> By client side validation you mean things like user form input?

Yes, so I'm probably using this library in an odd way, but the user will make various changes throughout the application. Most of their changes will have form/other levels of validation. The user will then attempt to sync their changes to the server. Before applying the changes I want to validate that all the schema is valid, in addition we will be validating the topology of any geographic features they may have edited. Again this is likely not a common case for other peoples applications, I wanted to implement in on the redux level because we support long editing sessions.

> You want to use createErrorAction to store errors inside requestReducer or there is another reason?

That was the thought, there might be a better place to implement the validation errors, but this would allow both server and client side errors to be handled in the rest of the app with the same logic

**Comment by klis87** [comment]
Did u think of formik/yup combo? This is what I use and it works very nice

**Comment by megawac** [comment]
So we're using `antd`forms & validation + `yup` on our end. The tricky part is when we want to validate the topology of geography. A real world example might be you cant have a parking space within 500m of this fire hydrant. Before we attempt to save these features that have invalid topology constraints we want to do a validation pass on the client side. I figured it might make sense to implement this validation on the redux level as I have complete access to all of the state of the map at this level.

**Comment by klis87** [comment]
If you really want to do this validation inside redux, I believe u have 2 options:
- do it within a custom middleware, just intercept request action, validate input, and on valid allow it, on invalid don't, you cannot do this in sagas easily as saga cannot prevent action dispatch, unless u would conditionally dispatch such requests only from sagas
- if you really need to do this as in your example, and to store errors in request reducer, I would just override `onError` of requests reducer not to decrement `pending` when for instance a `meta.clientSide` is true

**Comment by megawac** [comment]
So we're using `antd`forms & validation + `yup` on our end. The tricky part is when we want to validate the topology of geography. A real world example might be you cant have a parking space within 500m of this fire hydrant. Before we attempt to save these features that have invalid topology constraints we want to do a validation pass on the client side. I figured it might make sense to implement this validation on the redux level as I have complete access to all of the state of the map at this level.
