### ISSUE TITLE
Operation request which requires state information

### ISSUE THREAD

**Issue by megawac** [klis87/redux-saga-requests#250]
I have run into a case quite frequently where I have an operation on a request which requires some state information before I can dispatch the request. So I run a `select` -> dispatching the request. However this causes me to have to dispatch 2 different actions: first we have to dispatch the action to run the saga, then we run the saga, then we call the request action.

The downside of this with `redux-act` is the user dispatches `action1` but they have to watch for `action2` on the store. Example:

```js
// Call to run set feature saga
const setFeaturesAction = createAction(`set ${type}`);

const _setFeaturesAction = createAction(`set ${type} internal`, ({ map, [type]: features }) => {
  return {
    request: {
      url: '/v2/maps/operations/',
      method: 'post',
      data: formatRPCCall(`set${typeCapitalized}`, {
        map_id: map.id,
        features,
      })
    },
  };
}, ({ map, [type]: features }) => ({ map, features }));

// Get some stuff from state then run _setFeaturesAction.
const setFeaturesSaga = function* ({ payload }) {
  const { map } = yield select(state.maps);
  return yield put({ map, ...payload });
};

const reducer = requestsReducer({
  actionType: getFeaturesAction,
  // stuff and things...


  operations: {
    [_setFeaturesAction]: {},
  }
}, baseReducer);


// User dispatches
function mapStateToProps(state) {
  return {
    data: state.data,
    operation: state.operations._setFeaturesAction
  };
}

function mapDispatchToProps(dispatch) {
  return {
    runOp: () => {
      dispatch(setFeaturesAction)
    }
  }
}
```

From a user perspective its a bit awkward to know the difference between `_setFeaturesAction` and `setFeaturesAction` to use the store. Do you have any suggestions to improve this pattern?

**Comment by klis87** [comment]
I had similar use case, at least I think they are similar, correct me if I am wrong. I had dynamic urls in multiple places requiring for example user id. It would be terrible always to inject such attr in every action. I solved it by `onRequest` interceptor, something like this:
```js
import { mapRequest } from 'redux-saga-requests/lib/helpers';

const interpolatePlaceholders = (config, {  user }) => {
  if (config.url.includes('{user}')) {
    config = { ...config, url: config.url.replace('{user}', user) };
  }

  return config;
};

function* onRequest(request) {
  const user = yield select(userIdSelector);

  return mapRequest(request, config =>
    interpolatePlaceholders(config, {  user }),
  );
}
```

Then, I could have an action like:
```js
const getUserBooks = () => ({
  type: 'GET_USER_BOOKS',
  request: {
    url: '{user}/books',
  }
});
```

Notice I don't need to pass user id to `getUserBooks`, it is solved in one place in `onRequest` interceptor.

Alternatively you could use `redux-thunk` to dispatch request action, as it has `getState` function ready to be called

**Comment by megawac** [comment]
That does seem like the same use case but I'm not sure I'm happy with the
approach as it seems a bit opaque. I suppose `redux-thunk` could be an
option but it also seems a bit strange to mix and match with saga. Then
again I'm not sure what the ideal solution would be.

When I was originally trying to solve this issue I went looking to see if
`operations` had a `getType` option or similar you could specify. Would
this be a reasonable alternative?

**Comment by klis87** [comment]
I will take a look and think about it.

Regarding redux-thunk, I also initially thought some time ago that it is strange to mix it with saga, but actually imho thunk is a perfect way to inject data from state directly without using payload. BTW, there is a topic that mentions, that `select` in sagas and `getState` in thunk is evil, that all data should be passed as args to action creators. For me this is silly, because then React components need to subscribe to those data they should not even no about just to pass them back to Redux :D It just couples components with Redux for no reason. 

Also, my solution `onRequest` may seem a but strange, but this could be as well implemented as callback style:
```js
const getUserBooks = () => ({
  type: 'GET_USER_BOOKS',
  request: {
    url: ({ user }) => `${user}/books`,
  }
});
```

**Comment by klis87** [comment]
I saw you closed your PR, but issue is still open. Does it mean that you dont want this anymore? I just don't know whether I should get back to it once I have some time.

**Comment by megawac** [comment]
Closed the PR because I want to think about the problem some more. I'm going to try both your solutions this week. I'll close this off if I like it, otherwise you can toss it in the bucket :)

**Comment by klis87** [comment]
Closing, I will add some recipies before version `1` once working on docs. To sum up use either `thunk` or `onRequest` interceptor, it would be also possible to implement it on the driver level
