### ISSUE TITLE
Best practice to transform responses?

### ISSUE THREAD

**Issue by rSensation** [klis87/redux-saga-requests#256]
What is the recommended way to perform action-specific transformations on response before it reaches reducers? I use axios and currently put my transformation logic in transformResponse property - the issue is that if any error occurs in my logic, axios interceptor process it and it makes it inconvenient for debugging.

Do you have any advice on what could be the better alternative?

PS: great job on this lib, really enjoying it so far!

**Comment by klis87** [comment]
Glad you like it :) Did you check `getData` in `requestsReducer` or `onSuccess` interceptor?

**Comment by rSensation** [comment]
I've checked getData but eventually ended up using my own reducers instead of requestsReducer. I haven't tried onSuccess though, but correct if I'm wrong: it's a global interceptor, right? Can you define onSuccess for a separate action?

**Comment by klis87** [comment]
it is global but you could inspect action type if u wanted to

anyway I would really recommend you to use `requestReducer`, it gives you a lot and also the future version of this library will have even higher level concept - a global manager of all requests - and you wont need to write reducers and selectors for remote state anymore, just actions

but if you really prefer to you your own reducer, you should transform this data in reducer body itself, this is what `getData` actually does. you can do `case success(REQUEST_TYPE)` and transform response data before returning

**Comment by rSensation** [comment]
Actually, after reading your previous answer more carefully. I start to think onSuccess interceptor is probably the best place to achieve what I want. I just need to write more generic interceptor that would check if action has certain property in its payload and apply it to the response.

Thanks for your help and keep up the good work!
