### ISSUE TITLE
Multiple createRequestInstance with different onError/onRequest interceptors

### ISSUE THREAD

**Issue by elja** [klis87/redux-saga-requests#267]
Hello there,

Is there any possible way to implement multiple sagas with `createRequestInstance` and `watchRequests` that will be independent from each other. I have multi-tenant application that have different levels: **authentication**, **administrator**, **organization** level. Each level should have a separate `createRequestInstance` with global interceptors. For example authentication level saga shouldn't attach any JWT tokens to the request, but administrator and organization level should, moreover organization level should attach current organization id to each request.

**Comment by klis87** [comment]
Hi,

Interesting use case. Currently I would recommend you to achieve this by a convention. For instance by prefixing request actions types from different levels, for instance `ORGANIZATION/FETCH_STH`, or by using `action.meta.layer = 'organization'`.

Then, you could just conditionally apply logic in your interceptors based on those. For example, onRequest interceptor could look like:
```js

const onRequestInterceptor = {
  organization: organisationOnRequest,
  administrator: administatorOnRequest,
};


function* onRequest(request, action) {
  const interceptor = onRequestInterceptor[action.meta.layer];
  return yield call(interceptor, request, action);
}
```

**Comment by elja** [comment]
thanks! it does make sense

**Comment by klis87** [comment]
@elja I am glad that this solution fits you. 

btw, in future version I will try to allow passing interceptors as array, so it will work like composing

maybe I will even add a method like `addInterceptor`, so that you could add interceptors dynamically, so you wont need to import all of them to pass in one place. It would be handy with code splitting of sagas
