### ISSUE TITLE
Use API Facade instead of request url

### ISSUE THREAD

**Issue by strdr4605** [klis87/redux-saga-requests#270]
In my project, I use API Facades to fetch data and saga looks like
```ts
export const handleGetItem: Saga = function*({
  payload,
}: PayloadAction<typeof ActionEnum.API_GET_REQUEST, Payload>): IterableIterator<any> {
  const { id }: Payload = payload;
  const facade: Facade = yield getContext(SagaContextEnum.facade);

  try {
    const storeItem: IItem = yield call(() => facade.getItem(id));
    yield put(actions.successGetItem(storeItem));
  } catch (err) {
    yield put(actions.errorGetItem(err));
  }
};
```

How can I pass `facade.getItem(id)` to the redux-saga-request action creator??
Is it possible to implement this feature in this library??

**Comment by klis87** [comment]
So you mean you dont want to interact with your server with REST?

If yes, probably you will need to write a facade driver. https://github.com/klis87/redux-saga-requests/blob/master/packages/redux-saga-requests-axios/src/axios-driver.js is how it is done for axios, you can also find fetch and graphql drivers here

**Comment by strdr4605** [comment]
@klis87, My facade uses axios
```ts
import { AbstractFacade, IFacadeConfig } from 'my-lib';
import { AxiosResponse } from 'axios';
import { ItemModel } from 'items';
import { ItemsServerType } from './types';
export class Facade extends AbstractFacade {
  constructor(config: IFacadeConfig) {
    super(config);
  }

  async getItems(id: string): Promise<ItemsServerType> {
    const response: AxiosResponse<ItemsServerType> = await this.client.get(`/${id}/list`);
    return response.data;
  }
}
```
How should I create the driver?
I initiate facade and access it using sagaContext.
I also need to pass the Facade method to the action creator.
How hard is to implement these features above you library (if I fork it)!

**Comment by klis87** [comment]
@strdr4605 the question is why do you need it? in my opinion this is just overabstraction. This library removes any need to create api modules like you did, instead of `getItems` method of your class, you can easily do:
```js
const getItems = id => ({
  type: 'GET_ITEMS',
  request: {
    url: `/${id}/list`
  }
});
```

**Comment by klis87** [comment]
Alternatively you could write promise middleware like recommended here: https://github.com/klis87/redux-saga-requests/issues/244

But promise middleware imho makes sense with some external APIs like firebase which provides you some functions/classes to interact with API. But for in-house API I am sure my suggestion will simplify your codebase a lot. I know that class can keep some common state for you api methods, but everything could be solved without class, if you have a use case which you think requires facade, let me know and I will show you how this can be handled with this library

**Comment by strdr4605** [comment]
@klis87, The backend provides the facades that frontend uses. If API URL is changed the Facade may remain and no changes in frontend required.

**Comment by klis87** [comment]
@strdr4605 ok, so I recommend to write promise driver like in mentioned topic. In the future I might add official promise driver, I will add it to my todo list

**Comment by strdr4605** [comment]
@klis87 is it possible to use redux-saga selectors with this library? 
Lets say I have the id in my store. And I don't what to pass it as payload for action, but use `select` from `redux-saga/effects` and get the id and put in in url?

**Comment by klis87** [comment]
@strdr4605 of course, if you dispatch request action like `yield put(getItems(id))`, then id can be from `yield select`

personally though, If I had some id which is part of many request actions, I would just use redux thunk, which makes your sagas clean, or works if you dispatch actions from react too:
```js
function getItems() {
  return (dispatch, getState) => {
    const id = idSelector(getState());
    
    return dispatch({
      type: 'GET_ITEMS',
      request: {
        url: `/${id}/list`
      }
    };
  };
}
```

In my apps I sometimes do also another thing, kind of magical but I find it very convenient:
```js
import { mapRequest } from 'redux-saga-requests/lib/helpers';

const interpolatePlaceholders = (config, { user }) => {
  if (config.url.includes('{user}')) {
    config = { ...config, url: config.url.replace('{user}', user) };
  }

  return config;
};


function* onRequest(request) {
  const user = yield select(userIdSelector);

  return mapRequest(request, config =>
    interpolatePlaceholders(config, { user }),
  );
}
```

By using request interceptor, I can then define actions like:
```js
const getItems = () => ({
  type: 'GET_ITEMS',
  request: {
    url: '/{user}/list'
  }
});
```

**Comment by strdr4605** [comment]
@klis87, Interesting approach, but if I use https://github.com/klis87/redux-saga-requests/issues/244#issuecomment-487880194 I can't modify promise with interceptor :smile: . I will discuss with the team about using this package without facades (not sure if the team will agree).
Maybe we can create our implementation for our needs.

**Comment by klis87** [comment]
@strdr4605 yeah, for facade you would need to use either thunk approach, or adjust my placeholder solution to allow passing callback to `request`, like:
const getItems = () => ({
  type: 'GET_ITEMS',
  request: ({ idFromSelectorInonRequest }) => myFacade.getSth(idFromSelectorInonRequest)
});

The only limitation is your imagination, adjusting my example could also be:
const getItems = () => ({
  type: 'GET_ITEMS',
  request: {
    url: ({ user }) => `/${user}/list`
  }
});

You are free to do any transformation of request action in onRequest before request is fired

**Comment by strdr4605** [comment]
@klis87, Sorry for bothering so much :relaxed: but I implemented 
```ts
export function createRequestsActions(env: EnvInterface): any {
  const placePickerFacade: PlacePickerFacade = new PlacePickerFacade({
    axiosConfig: {
      baseURL: env.PLACE_PICKER_URL,
    },
  });

  const requestGet: any = (merchantId: string, sessionId: string): object => ({
    type: LocationsActionEnum.API_LOCATIONS_GET_REQUEST,
    payload: {
      request: placePickerFacade.getStoreLocations(merchantId, sessionId),
    },
  });

  return {
    requestGet,
  };
}

export const createDriver: () => Driver = (): Driver => ({
  requestInstance: null,
  getAbortSource(): null {
    return null;
  },
  abortRequest(): void {},
  async sendRequest(promise: Promise<StoreLocationServerResponse>): Promise<StoreLocationServerResponse> {
    return promise;
  },
  getSuccessPayload(response: StoreLocationServerResponse): StoreLocationServerResponse {
    return response;
  },
  getErrorPayload(error: Error): Error {
    return error;
  },
});

export const locationsReducerNew: Reducer = requestsReducer({ actionType: LocationsActionEnum.API_LOCATIONS_GET_REQUEST });
```
and the action is dispatched but no success or error action triggered 
![Screenshot from 2019-08-14 15-06-10](https://user-images.githubusercontent.com/16056918/63019940-67b04f80-bea5-11e9-8e6d-d73d1fddc35f.png)

Can be a problem that I did not implement the driver correctly?

**Comment by klis87** [comment]
I can see 2 issues:
export const createDriver: () => Driver = (): Driver => ({ which is duplicated return

  async sendRequest(promise: Promise<StoreLocationServerResponse>): Promise<StoreLocationServerResponse> {
    return promise;
  },

u return promise in async function, so actually you return promise of promise, remove async

**Comment by strdr4605** [comment]
@klis87, `() => Driver` is the type for typescript of the **createDriver**, so there is no dublication.

```js
async sendRequest(promise: Promise<StoreLocationServerResponse>): Promise<StoreLocationServerResponse> {
    return promise;
  },
```
Typescript requires the function to be `async` if it returns a promise. From what I understood the driver should handle it correctly. 

Anyway, thank you for helping! You can label this issue as a **question** and let it open or close!

**Comment by klis87** [comment]
@strdr4605 I am surprised as 
```ts
const x = () => {
  return new Promise(resolve => resolve(1));
};
```
does not show any TS errors.

Anyway, I am closing this issue in favour of #244
