### ISSUE TITLE
with next.js

### ISSUE THREAD

**Issue by rumsky** [klis87/redux-saga-requests#282]
How to use it with next.js

**Comment by klis87** [comment]
@rumsky do you have any specific questions? I never used next.js. The only reason I would is server side rendering, but this library has 1st class support for ssr within redux. 

Anyway, if you know how to use redux with next.js, then there should not be any specific thing regarding adding this library. This is just redux/redux-saga addon. Do you have any specific issues?

**Comment by klis87** [comment]
Close due to inactivity
