### ISSUE TITLE
use networkReducer with React Redux HOC

### ISSUE THREAD

**Issue by baswieb** [klis87/redux-saga-requests#284]
I would like to use the new networkReducer in a React Redux connect in a HOC.
In mapStateToProps I tried to use getQuery but that function does not return a result.
All your examples are using React Hooks.
Is there another solution to use getQuery with React Redux connect?

**Comment by klis87** [comment]
@baswieb is there any reason you dont wanna use React hooks? 

Anyway, it is possible to use `getQuery` like a normal selector with `mapStateToProps`, but remember, `getQuery` is actually a selector creator, so for instance:
```js
const booksSelector = getQuery({ type: 'FETCH_BOOKS' });

const mapStateToProps = state => ({ books: booksSelector(state) });

```

**Comment by baswieb** [comment]
> @baswieb is there any reason you dont wanna use React hooks?
I have several older components in my project that I don't want to convert yet. I will use React Hooks for new components in the project.

Your solution works. Thanks!

I needed this because I can't use the networkReducer and my old requestReducers together in one project.
If I use them both all the data is available twice in the store.

**Comment by klis87** [comment]
but `useQuery` or `Query` is also compatible with state from `requestsReducer`

Anyway, pls note that in future versions only `networkReducer` will be available, as only predictable remote data structure would allow me to add next features I am working on. So I highly recommend you to switch everything to `networkReducer` at some point.

**Comment by baswieb** [comment]
> Anyway, pls note that in future versions only `networkReducer` will be available

That's why I needed getQuery in React Redux connect so I can remove all the requestReducers and change all the connected components to use the networkReducer.
Thanks for this nice library!
