### ISSUE TITLE
TypeError: request.query.trim is not a function

### ISSUE THREAD

**Issue by strdr4605** [klis87/redux-saga-requests#289]
As I created my own implementation of Promise actions https://github.com/klis87/redux-saga-requests/issues/244#issuecomment-534006125

when using **watchRequests**
```ts
export const rootSaga: Saga = function*(): any {
  yield createRequestInstance({ driver: createDriver() });
  yield all([watchRequests(), fork(watcherMerchant), fork(watcherUser)]);
};
```
**TypeError: request.query.trim is not a function isRequestQuery actions.js:121:122** is thrown.

-----------------------
Also, I tried using [networkReducer](https://github.com/klis87/redux-saga-requests#networkreducer) as requestsReducer may be deprecated, and same error is thrown even when in the saga, the first approach is used
```ts
import { createRequestInstance, sendRequest } from 'redux-saga-requests';

export const rootSaga: Saga = function*(): any {
  yield createRequestInstance({ driver: createDriver() });
  yield takeLatest(LocationsActionEnum.NEW_API_LOCATIONS_GET_REQUEST, sendRequest);
  yield all([fork(watcherMerchant), fork(watcherUser)]);
};
```

**Comment by klis87** [comment]
@strdr4605 yeah, that is the consequence of abusing query, which was designed for graphql.

Try this for now:
```js
const fetchBooks = promise => ({
  type: 'FETCH_BOOKS',
  request: { url: promise },
});
```

I know, this is silly to put promise inside url, but it is the only way to be compatible with current `isRequestAction` and `isRequestQuery` checks.

Also, for mutations do:
```js
const deleteBooks = promise => ({
  type: 'DELETE_BOOKS',
  request: { url: promise },
  meta: { asMutation:  true },
});
```

as `networkReducer` needs to know whether sth is a query or a mutation.

Anyway, the next version of this library will allow those things to be configurable. Also, promise driver will be officially included as additional package.
