### ISSUE TITLE
[question] Where can I find source code for multiple requests per action?

### ISSUE THREAD

**Issue by yieldinov** [klis87/redux-saga-requests#302]
> sending multiple requests in one action - { type: FETCH_BOOKS_AND_AUTHORS, request: [{ url: '/books' }, { url: '/authors}'] } will send two requests and wrap them in Promise.all

Where is this `Promise.all()` in code?

**Comment by klis87** [comment]
https://github.com/klis87/redux-saga-requests/blob/master/packages/redux-saga-requests/src/sagas/send-request.js#L91

I used `all` effect from redux saga, but it works like Promise.all, possibly Promise.all is used under the hood anyway

**Comment by klis87** [comment]
Closed due to inactivity
