### ISSUE TITLE
How to get response data after mutation without custom reducer.

### ISSUE THREAD

**Issue by svindler** [klis87/redux-saga-requests#305]
Hello,

I'm using the networkReduxer, but after reading the docs couple times can't find an easy way to get the data after a mutation without creating a custom reducer. 

These are my actions:

```
const doFetchQuestion = id => ({
  type: FETCH_QUESTION,
  request: {
    url: `/api/questions/${id}`,
  },
  meta: {
    abortOn: CLEAR_QUESTION,
    resetOn: [CLEAR_QUESTION],
    mutations: {
      [SAVE_QUESTION]: {
        updateData: true
      },
    },
  },
});

const doClearQuestion = () => ({
  type: CLEAR_QUESTION,
});

const doSaveQuestion = question => ({
  type: SAVE_QUESTION,
  request: {
    url: `/api/questions`,
    method: 'POST',
    data: question,
  },
});
```

Please point me to the right directon.

Thanks!

**Comment by klis87** [comment]
With `networkReducer` u put mutations not to query but mutation, like:

```js
const doSaveQuestion = question => ({
  type: SAVE_QUESTION,
  request: {
    url: `/api/questions`,
    method: 'POST',
    data: question,
  },
  meta: 
   id: question.id,
   mutations: {
      [FETCH_QUESTION]: {
       updateData: (state, action) =>
          state.data.map(v => v.id === action.meta.id ? action.data : v),
      },
    },
});
```

I can totally understand though it is confusing. In the future version only `networkReducer` will be supported, so it will be easier to explain in docs.

Also there won't be any internal state in `networkReducer`, so this `id: question.id,` in `meta` wont be necessary anymore as normal javascript closure will suffice. Here won't as `mutations` config is added only once for each action of a given type, so id would be fixed, hence this meta trick so u can get id from responseAction in updateData. Please live it for now, next release will fixed all those problems.

**Comment by svindler** [comment]
Thank you for your quick reply. 

I trigger this action on form submission, so I don't have an ID yet. I tried the mutation in the doSaveQuestion action but the updateData function doesn't gets called.

**Comment by klis87** [comment]
See example especially this file and line to see mutations in action

**Comment by klis87** [comment]
Regarding id I though doSaveQuestion is for updating. If this is for creation, then update data could just append new question so id is not necessary then

**Comment by svindler** [comment]
I'm using mutations with delete, they work as they should, but no luck with post requests. Thanks!

**Comment by klis87** [comment]
Logic should be exactly the same, if u still have issues pls make minimal reproducing repo so I could take a look

**Comment by klis87** [comment]
@svindler let me know if sth does not work, it really should, especially in v0.27.0
