### ISSUE TITLE
 [redux-saga-requests-graphql]Argument of type 'TemplateStringsArray' is not assignable to parameter of type 'string'.

### ISSUE THREAD

**Issue by fhourdin** [klis87/redux-saga-requests#309]
Typescript seems to be crying when I try to use "gql" from "redux-saga-requests-graphql"
Can be resolved by adding "TemplateStringsArray" as a possible type for "gql" arguments.
Pull request in progress

btw, your lib rocks

```
ERROR in /<<workspace>>/actions.tsx(7,15):
7:15 Argument of type 'TemplateStringsArray' is not assignable to parameter of type 'string'.
     5 |   type: anAction,
     6 |   request: {
  >  7 |     query: gql`
       |               ^
     8 |       {
     9 |         a request
```

**Comment by klis87** [comment]
Could you please show me full snippet here which breaks types?

below https://github.com/klis87/redux-saga-requests/blob/master/packages/redux-saga-requests-graphql/types/index.d.spec.ts#L7 locally I added:
```js
gql(`
  query{
    obj {
      id
    }
  }
`);
```
and it works. I just wanna make sure that this is really needed. Then I will merge your PR. Thanks!

**Comment by klis87** [comment]
Sry my bad, actually bracket is wrong here. I am not sure but probably this should be just `TemplateStringsArray`, not `string | TemplateStringsArray`

Please confirm and adjust your PR or give me example when `string` fits `gql`

**Comment by klis87** [comment]
I tried this:
```js
gql`
  query{
    obj {
      id ${'1'} ${2}
    }
  }
`;
```
I believe the correct type is actually

```ts
export const gql: (
  query: TemplateStringsArray,
  ...args: (string | number)[]
) => string;
```
```

**Comment by fhourdin** [comment]
Sounds good ! I'll fix that

**Comment by fhourdin** [comment]
Are regular strings passing the TemplateStringsArray type ?

**Comment by klis87** [comment]
I think this wont be possible for gql, because gql function can actually be used only with template literals

So 
```js
gql`query`
```
 will work.
 `gql'query'` though is incorrect syntax, if this is what you meant.

**Comment by klis87** [comment]
Just merged. The only problem is that PR was to `dev`, which wont be merged to master soon, as there is huge work to be done before this happens. See https://github.com/klis87/redux-saga-requests/issues/306

If you need this now, pls create PR to master directly

**Comment by klis87** [comment]
@fhourdin merged in newest version
