### ISSUE TITLE
[Solved] ERROR action not triggered

### ISSUE THREAD

**Issue by strdr4605** [klis87/redux-saga-requests#311]
@klis87, I have a bug when implementing the workaround with promises. My driver is as in https://github.com/klis87/redux-saga-requests/issues/244#issuecomment-534006125. And the request is triggered and the `SUCCESS` is coming ok. But then there is an error from backend `SUCCESS` is triggered instead of `ERROR`.

I tried several options.

```js
const requestGetUrls = (merchantId) => ({
        type: actions_1.MerchantActionEnum.API_URLS_GET_REQUEST,
        payload: {
            request: {
                url: axios_1.get('https://jsonplaceholder.typicode.com/users/11'),
            },
        },
    });
```
```js
const requestGetUrls = (merchantId) => ({
        type: actions_1.MerchantActionEnum.API_URLS_GET_REQUEST,
        payload: {
            request: {
                url: webMerchantFacade.urls(merchantId),
            },
        },
    });
```
```js
const requestGetUrls = (merchantId) => ({
        type: actions_1.MerchantActionEnum.API_URLS_GET_REQUEST,
        payload: {
            request: {
                url: 'https://jsonplaceholder.typicode.com/users/11',
            },
        },
        meta: {
          driver: 'axios'
        }
    });
```
All of the actions above resolve in `SUCCESS` instead of `ERROR`. Also, I tried **networkReducer** but still the same behavior.

> Even with axios driver, there is the same problem. So maybe the problem is not in my driver.

Interesting is that when I pass a rejected Promise 
```js
const requestGetUrls = (merchantId) => ({
        type: actions_1.MerchantActionEnum.API_URLS_GET_REQUEST,
        payload: {
            request: {
                url: Promise.reject('error'),
            },
        },
    });
```
The `ERROR` action is triggered.

I made a dummy project https://codesandbox.io/s/redux-saga-requests-example-x4bf6 but there everything works as expected.

Maybe you have an Idea where can be the problem.

**Comment by strdr4605** [comment]
@klis87,
what I found by debugging `node_modules/redux-saga-requests/lib/sagas/send-request.js`

```js

...
...

case 44:
  _context.prev = 44;
  _context.t0 = _context["catch"](28);
  // Here the eror is catched and responseError is a Error Object
  console.log({error: _context.t0});

  responseError = _context.t0;

...
...

case 57:
  // I log here the response and it is an object
  console.log({response});

  // So this "if" will break and call driver.getErrorPayload, will not be triggered
  if (response) {
     _context.next = 65;
     break;
  }

  _context.next = 60;
  return (0, _effects.call)(driver.getErrorPayload, responseError);

...
...

```

![image](https://user-images.githubusercontent.com/16056918/73527944-99e64700-441c-11ea-889e-67199b6d1e46.png)

I changed the source code to 

```js

case 57:
  // I log here the response and it is an object
  console.log({response});

  // Check if no Error
  if (!responseError) {
     _context.next = 65;
     break;
  }

  _context.next = 60;
  return (0, _effects.call)(driver.getErrorPayload, responseError);

...
...

```

This means that [here](https://github.com/klis87/redux-saga-requests/blob/master/packages/redux-saga-requests/src/sagas/send-request.js#L123) it should be like below in order to work.

```diff
- if (!response) {
+ if (responseError) {
        const errorPayload = yield call(driver.getErrorPayload, responseError);

        if (!silent) {
          yield put(createErrorAction(action, errorPayload));
        }

        return { error: responseError };
      }
```

I don't know why the `response` variable is filled with the error response from the server but maybe this fix will work for any other cases. 

Let me know what do you think as I already spent 3 days on debugging. So if the solution will not be found we will have to remove `redux-saga-requests` and go back to the old version of handling requests :cry:.

**Comment by strdr4605** [comment]
The problem was what a long time ago I wrote an interceptor.

```ts
export function* onErrorSaga(error: AxiosResponse, action: AnyAction): Iterator<AxiosResponse | Effect<any>> {
  ...
  ...
  return error;
}
```
and was returning the error object. But axios has a `response` property in the error that was interpreted by the `redux-saga-requests` as a legit response.

To fix the issue I changes the return value as in [interceptors docs](https://github.com/klis87/redux-saga-requests/tree/master/packages/redux-saga-requests#interceptors-arrow_up).
```ts
export function* onErrorSaga(error: AxiosResponse, action: AnyAction): Iterator<AxiosResponse | Effect<any>> {
  ...
  ...
  return { error };
}
```

**Comment by klis87** [comment]
@strdr4605 Thx for sharing this and I am glad you solved it!
