### ISSUE TITLE
How would I add a retry mechanism?

### ISSUE THREAD

**Issue by denchen** [klis87/redux-saga-requests#59]
I currently have my own implementation of Redux Saga & axios (albeit a not very good one as I'm still learning how to use Redux Saga) when I came across your library. I'm exploring if it'll work for my project. The basic question is, how would I implement a retry mechanism? My code currently looks something like:

    import { delay } from 'redux-saga';
    import { call, cancelled } from 'redux-saga/effects';

    const RETRIES = 5;
    const RETRY_DELAY = 2000;

    export function* callApi(url) {
      let error;
      let cancelToken = axios.CancelToken;
      let source = cancelToken.source();
      for (let i = 0; i <= RETRIES; i++) {
        try {
          return yield axios.get(url, {
            cancelToken: source.token
          });
        } catch (err) {
          error = err;
          if (
            err.response &&
            err.response.status >= 400 &&
            err.response.status <= 499
          ) {
            // Ignore 4xx errors.
            break;
          }
          if (i < RETRIES) {
            yield call(delay, RETRY_DELAY);
          }
        } finally {
          if (yield cancelled()) {
            source.cancel('Cancelling axios');
          }
        }
      }
    }

So I want to retry failed requests, but only if they're not 4xx. Using your library, I'm not sure where this logic would go.

**Comment by klis87** [comment]
It should be possible using interceptors, unfortunately currently they won't allow you to do this, you can only dispatch some actions on request, response, error and abort, but you cannot for example catch error and convert it into a successful response - its on my TODO list.

Still, for now, you can use Axios interceptors! I will give you a snippet I used with refreshing token login, it is still kind of retry:
1) I make an API call
2) I get 401 eror because my token expired
3) I get a new token with refresh token
4) I repeat API call from point 1)

Here you can see the snippet:
```js
import axios from 'axios';
import { createRequestInstance } from 'redux-saga-requests';
import axiosDriver from 'redux-saga-requests-axios';

const createApiInstance = () => {
  const instance = axios.create({
    baseURL: process.env.DATABASE_URL,
  });

  instance.interceptors.request.use(config => {
    const token = window.localStorage.getItem('token');

    if (token) {
      return {
        ...config,
        params: { ...config.params, token },
      };
    }
    
    return config;
  });

  const is401 = error => error.response && error.response.status === 401;

  instance.interceptors.response.use(
    response => response,
    error => {
      if (typeof window === 'undefined') {
        throw error;
      }

      const refreshToken = window.localStorage.getItem('refreshToken');

      if (refreshToken && is401(error)) {
        return instance
          .post('/refresh-token', { refreshToken })
          .then(({ data }) => {
            const newToken = data.token;
            window.localStorage.setItem('token', newToken);
            const config = {
              ...error.config,
              params: { ...error.config.params, token: newToken },
            };
            return instance(config);
          })
          .catch(refreshTokenError => {
            console.log('refresh token error', refreshTokenError);
            throw error;
          });
      }

      throw error;
    },
  );

  return instance;
};

function* rootSaga() {
  yield createRequestInstance(createApiInstance(), { driver: axiosDriver });
  // use watchRequests or sendRequest like in docs
}
```

This is 1 time retry with a new token, but you could convert this snippet to your use case as well. The only downside is that you cannot use saga effects to make this simple.

Once I implement similar interceptors to Axios, this task will be match easier, and as a bonus, you won't even need to handle aborting request - this library handles this automatically for you.

**Comment by denchen** [comment]
Thanks for the response. I mostly follow your code snippet, except to the part in the error handler where you `return instance(config);`. So by returning `instance`, that restarts the API request? How does that happen?

In any case, with a few modifications, I got a version of your snippet working. I had to modify it to not only handle retries but also handle multiple simultaneous fetches going at once (so I'm using `takeEvery()` instead of `takeLatest()`). However, it feels like a hack. The relevant portions:

    const createApiInstance = () => {
      let retries = {};
      
      instance.interceptors.request.use(config => {
        if (!retries[config.url]) {
          // Each simultaneous fetch should have a unique URL
          retries[config.url] = NUM_RETRIES;
        }
        return config;
      });

      instance.interceptors.response.use(
        response => {
          delete retries[response.url];
          return response;
        },
        error => {
          if (--retries[error.config.url] > 0 && !is4xx(error)) {
            return instance(error.config);
          }
          delete retries[error.config.url];
          throw error;
        }
      }

I'm not sure if there's a better way of handling it. In any case, I definitely look forward to your implementations to make all this easier.

**Comment by denchen** [comment]
Oh, one more unrelated note: For some reason, using this library, I get an error:

    ReferenceError: regeneratorRuntime is not defined

I found a [similar issue over on redux-saga](https://github.com/redux-saga/redux-saga/issues/280), and the fix for me is I basically had to add to my root `index.js`:

    import 'regenerator-runtime/runtime';

I'm not sure what the root cause of this is, if this is an issue with your library or Redux Saga or a configuration issue on my part. I'm using Create React App (not ejected), in case that's helpful.

**Comment by klis87** [comment]
In my code snippet, `instance` is an axios instance, and `axios.get('/url')` is really the same as `axios({ url: '/url', method: 'get' })`, which relates to `instance({ url: '/url', method: 'get' })`, where `{ url: '/url', method: 'get' }` is the `config`. So, in line `return instance(config);` a new request with the same `config` is repeated, which will again go through axios interceptors.

`takeLatest` didn't work for your case? if a new request should cancel previous one, this is the effect to use. And, with this library, when a saga is cancelled, request itself is cancelled as well, for example with `race` and `takeLatest` effects - see advanced example.

Regarding `ReferenceError`, this is related to using ES6 generators, which you must use when  using redux-saga. The easiest and most recommended thing to do is just installing and importing `babel-polyfill`, especially with `babel-preset-env`, see https://babeljs.io/docs/usage/polyfill/ and https://babeljs.io/docs/plugins/preset-env/

I will try to improve interceptors in this library within 2 weeks time span, but no promises ;)

**Comment by denchen** [comment]
Thanks for the `instance` explanation.

I'm intentionally using `takeEvery` since I have several components that independently (and simultaneously) will be dispatching the same `FETCH_POST` action with different API endpoints (eg. `/api/groups/1`, `/api/groups/2`). In my previous implementation, I had logic to correctly cancel the right Saga by also sending a payload with a unique identifier so the saga ends like like:

    function* fetchPost = (action) => {
      const { response, cancel } = yield race({
        response: call(callApi, action.url, action.params, action.reload),
        cancel: take(({ type, payload }) => {
          return type === CANCEL_FETCH_POST && payload.key === action.payload.key;
        })
      });
    });

I'll probably end up doing something very similar using your library.

Also, thanks for the `ReferenceError` explanation!

**Comment by klis87** [comment]
I see, group id can be different and you need more than 1 to load, so right, you cannot use `takeLatest` here.

I am glad you consider using my library :)  I will let you know once interceptors are done, then you could tell me whether they will be enough for your use case.

**Comment by denchen** [comment]
Thanks! So far your library does seem to suit my needs. I'll need to more fully integrate with the rest of my app to be sure.

I do have one more question. I probably should open a new issue for this, but how would I go about integration testing? For unit testing, I'm using [`redux-saga-test-plan`'s `testSaga()`](http://redux-saga-test-plan.jeremyfairbank.com/unit-testing/). But I want to test the entire lifecycle of a Saga, from dispatching initial action to populating the state. Given your race/sendRequest example in the README (which is pretty much how I'm using your library now), I'm not sure the best path. `redux-saga-test-plan` also has an [`expectSaga()`](http://redux-saga-test-plan.jeremyfairbank.com/integration-testing/) that I've been using for simpler sagas, but for this case, I'll need to mock some stuff, like axios (maybe via [moxios](https://github.com/axios/moxios) or [axios-mock-adapter](https://github.com/ctimmerm/axios-mock-adapter)). Would I need to mock `sendRequest` as well? Or can I use `sendRequest` in a testing environment? If so would I have to use `createRequestInstance` in my testing as well since `sendRequest` relies on the driver being set up?

Again, thanks for your help thus far.

**Comment by klis87** [comment]
For unit testing I use official saga approach with iterating over generator with `next` and `send`, but this is too close to implementation and I also wanna switch to sth like https://github.com/jfairbank/redux-saga-test-plan, https://github.com/wix/redux-saga-tester or https://github.com/antoinejaussoin/redux-saga-testing .

For integration test, if you dispatch a request action with `sendRequest` with axios driver with whole lifecycle of saga, axios requests will be fired. So, you have following options:
- mocking axios like u mentioned
- replacing axios driver with inMemory home made driver just for test purposes - I would like to include it into this repo but this is on TODO list
- maybe unit test is enough? maybe all you should care about is that on  Request a corresponding success or error action is dispatched?
- if you wanna test really the whole environment, maybe you should consider real integration test, with Selenium for instance?

**Comment by denchen** [comment]
Yeah, I've been using `redux-saga-test-plan`, but the unit tests almost seem pointless. For example, if I have:

    export function* fetchData(action) {
      yield race([
        call(sendRequest, action),
        take(CANCEL_FETCH)
      ])
    )

Then the unit test written in redux-saga-test-plan for this would be:

    it('sets up a race', () => {
      const saga = testSaga(fetchData, action);

      saga
        .next()
        .race([call(sendRequest, action), take(CANCEL_FETCH)])
        .finish()
        .isDone();
    });

I'm pretty much repeating what's in the original code, so I don't really see any value-add. That's why I wanted more integration-type of testing. And I actually got it working with your library and redux-saga-test-plan. Here's a sample test:

    let withSagaRequests;
    beforeEach(() => {
      withSagaRequests = function*() {
        yield createRequestInstance(createApiInstance(), { driver: axiosDriver });
        yield fetchDataSaga();
      };
      moxios.install(); // Using moxios to mock API call
    });

    test('fetchData flow', () => {
      // Mock axios call
      moxios.stubRequest('/api/v1/costs/foo', {
        status: 200,
        responseText: { foo: 'bar' }
      });

      return expectSaga(withSagaRequests)
        .withReducer(fetchDataReducer)
        .hasFinalState({ data: { foo: 'bar' }, error: null, pending: 0  })
        .put.actionType(success(FETCH_DATA))
        .dispatch({
          type: FETCH_DATA,
          payload: { request: { url: '/api/v1/costs/foo' } }
        })
        .silentRun();
      });
    });

So the key thing is, I had to test my `fetchDataSaga` by integrating with `createRequestInstance`. The test makes a dispatch (`FETCH_DATA`), and I check for the final state produced by the reducer.

I was hoping for something a little cleaner than this, but the key thing is that it works. And yes, testing the whole environment via something like Selenium is on my to-do list as well.

**Comment by klis87** [comment]
Maybe inMemoryDriver would make it better? anyway, I like your test and really this is how one should test saga, you can really know that your soft is working :+1:

**Comment by klis87** [comment]
@denchen I added new interceptors, they should be enough to cover request retries, if not, please let me know
