### ISSUE TITLE
Dynamically changing request config

### ISSUE THREAD

**Issue by vomchik** [klis87/redux-saga-requests#64]
Hi!

How can I dynamically change request config? 

In my case, i need set auth token to the headers prop.

**Comment by klis87** [comment]
Hi!

Every request config can be dynamic, as this is just a redux acion with `request` key. So, for example, to generate a request with auth header, you could:
```js
const authRequest = token => ({
  type: 'AUTH_REQUEST',
  request: {
    url: '/some-url',
    headers: { 'auth-header': token },
  }
})
```
If you have to pass token in many different request types, you could consider adding this header globally in interceptors. Currently I need to work on interceptors in this library a bit to allow this, but you could use `axios` interceptors. See #59 for some snippets and ideas.

**Comment by vomchik** [comment]
Understood you, thanks.
