### ISSUE TITLE
Error from API comes empty

### ISSUE THREAD

**Issue by pitakill** [klis87/redux-saga-requests#68]
I have implemented this project into my early work for a newly created SPA.

My successful responses come into the State of Redux as expected. But the error responses come in a empty `error` in the State of Redux, but the response from the API seems to look ok to me.

![image](https://user-images.githubusercontent.com/478407/35982295-0fc19318-0cb5-11e8-8252-fbc15e1a7c6b.png)

![image](https://user-images.githubusercontent.com/478407/35982348-303ef22a-0cb5-11e8-9803-655fe431129a.png)

If you could enlightenment me about it, it good be awesome.

UPDATE: I'm using `fetch` driver, without a polyfill and using Google Chrome: 64.0.3282.140 (Official Build) (64-bit) in MacOS High Sierra

Thanks for this work, is pretty awesome. :-)

**Comment by pitakill** [comment]
Maybe this behavior with `Fetch` has to be related: https://www.tjvantoll.com/2015/09/13/fetch-and-errors/

**Comment by klis87** [comment]
@pitakill This is probably serialization problem of redux dev tools. Did you try to `console.log(error`) in your reducer/selector/component?

**Comment by pitakill** [comment]
@klis87 I can see clearly now. The `error` in the state is a `Response` from `Fetch`, so I'm figuring out how to responde with the `response.json()` in the `onError` my attempt it is:

![image](https://user-images.githubusercontent.com/478407/35987686-06ed5242-0cc2-11e8-9839-d50f672d8209.png)

![image](https://user-images.githubusercontent.com/478407/35987822-6ac8b4be-0cc2-11e8-82ca-0b1eb3ae3530.png)


Thank your for your time and support. :-)

**Comment by klis87** [comment]
So you try to use interceptors for this, this really should work but I guess it won't, at least not until I will improve interceptors in this library, which is on my list. Now you have for instance dispatch some actions in interceptors, but return value of interceptors is not taken into account yet (which is really wrong I know:)).

What you could do know is to overwrite `getErrorPayload` in official fetch driver before passing it to `createRequestInstance` - see https://github.com/klis87/redux-saga-requests/blob/master/packages/redux-saga-requests-fetch/src/fetch-api-driver.js#L39

**Comment by pitakill** [comment]
Thank you a lot!

![image](https://user-images.githubusercontent.com/478407/35989408-afd96892-0cc6-11e8-8531-9e58198a0974.png)

Works like a charm! :-)

I'm going to try to send you a PR with the changes in your comment above. :-)

**Comment by klis87** [comment]
Great! One thing I am a little worried about, returning only `responseError.json()` will include all error data which might be useful? If not, I guess it can be safely added to fetch driver itself, despite the fact it would be a breaking change :)

**Comment by klis87** [comment]
@pitakill Just see a new version of Fetch driver - https://github.com/klis87/redux-saga-requests/releases/tag/redux-saga-requests-fetch%400.7.0

You don't need to use `response.json()` anymore anywhere, just read `response.data`.
